//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GuMeiDBEntities : DbContext
    {
        public GuMeiDBEntities()
            : base("name=GuMeiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<S_city> S_city { get; set; }
        public virtual DbSet<S_dict> S_dict { get; set; }
        public virtual DbSet<S_dicttype> S_dicttype { get; set; }
        public virtual DbSet<S_environment> S_environment { get; set; }
        public virtual DbSet<S_menu> S_menu { get; set; }
        public virtual DbSet<S_role> S_role { get; set; }
        public virtual DbSet<S_role_menu> S_role_menu { get; set; }
        public virtual DbSet<S_user> S_user { get; set; }
        public virtual DbSet<S_user_log> S_user_log { get; set; }
        public virtual DbSet<S_user_loginerror> S_user_loginerror { get; set; }
        public virtual DbSet<S_user_role> S_user_role { get; set; }
        public virtual DbSet<S_user_validatenum> S_user_validatenum { get; set; }
        public virtual DbSet<T_CareApply> T_CareApply { get; set; }
        public virtual DbSet<T_DemandApply> T_DemandApply { get; set; }
        public virtual DbSet<T_Elderly> T_Elderly { get; set; }
        public virtual DbSet<T_ExchangeRecord> T_ExchangeRecord { get; set; }
        public virtual DbSet<T_HelpAgeAgency> T_HelpAgeAgency { get; set; }
        public virtual DbSet<T_LifeApply> T_LifeApply { get; set; }
        public virtual DbSet<T_LifeServiceAgency> T_LifeServiceAgency { get; set; }
        public virtual DbSet<T_MedicalAgency> T_MedicalAgency { get; set; }
        public virtual DbSet<T_MedicalApply> T_MedicalApply { get; set; }
        public virtual DbSet<T_News> T_News { get; set; }
        public virtual DbSet<T_PensionAgency> T_PensionAgency { get; set; }
        public virtual DbSet<T_PensionApply> T_PensionApply { get; set; }
        public virtual DbSet<T_PensionProduct> T_PensionProduct { get; set; }
        public virtual DbSet<T_PublicApply> T_PublicApply { get; set; }
        public virtual DbSet<T_PublicServiceAgency> T_PublicServiceAgency { get; set; }
        public virtual DbSet<T_recordServers> T_recordServers { get; set; }
        public virtual DbSet<T_RescuePersonnel> T_RescuePersonnel { get; set; }
        public virtual DbSet<T_RescuePersonnelApply> T_RescuePersonnelApply { get; set; }
        public virtual DbSet<T_ServicePersonnel> T_ServicePersonnel { get; set; }
        public virtual DbSet<T_SocialPensionApply> T_SocialPensionApply { get; set; }
        public virtual DbSet<T_StreetHelpAgeApply> T_StreetHelpAgeApply { get; set; }
        public virtual DbSet<T_StreetPensionApply> T_StreetPensionApply { get; set; }
    }
}
