//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_dict
    {
        public int Id { get; set; }
        public string Typecode { get; set; }
        public int Sort { get; set; }
        public string Code { get; set; }
        public string Name_cn { get; set; }
        public string Name_hk { get; set; }
        public string Name_en { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public string Value3 { get; set; }
        public string Remark { get; set; }
        public string Isdeleted { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public Nullable<int> Createuserid { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public Nullable<int> Updateuserid { get; set; }
    }
}
