//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_menu
    {
        public int Id { get; set; }
        public string Menukind { get; set; }
        public string Menuid { get; set; }
        public string Menuname_zho { get; set; }
        public string Menuname_eng { get; set; }
        public string Pmenuid { get; set; }
        public int Islastlevel { get; set; }
        public string Orderseq { get; set; }
        public long Menuactions { get; set; }
        public int Showallways { get; set; }
        public string Menuobject { get; set; }
        public string Menuurl { get; set; }
        public string Menuparams { get; set; }
        public string Menuiconsmall { get; set; }
        public string Menuiconmiddle { get; set; }
        public string Menuiconlarge { get; set; }
        public int Iscontextmenu { get; set; }
        public int Istoolbarmenu { get; set; }
        public int Isshortcutmenu { get; set; }
        public int Showtopsep { get; set; }
        public int Showbottomsep { get; set; }
        public string Tag_1 { get; set; }
        public string Tag_2 { get; set; }
        public string Tag_3 { get; set; }
        public string Tag_4 { get; set; }
        public string Tag_5 { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public string Createuser { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public string Updateuser { get; set; }
        public string Updateip { get; set; }
    }
}
