//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_user_validatenum
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Mobilenum { get; set; }
        public string Validatetype { get; set; }
        public string Validatenum { get; set; }
        public Nullable<System.DateTime> Expiretime { get; set; }
        public string Sessionid { get; set; }
    }
}
