//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_user_loginerror
    {
        public int Id { get; set; }
        public int User_id { get; set; }
        public string Username { get; set; }
        public int Oprttype { get; set; }
        public System.DateTime Oprttime { get; set; }
        public string Clientid { get; set; }
        public string Ip { get; set; }
        public string Comments { get; set; }
        public int Errortimes { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public Nullable<int> Createuserid { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public Nullable<int> Updateuserid { get; set; }
    }
}
