//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_user
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Realname { get; set; }
        public string Usertype { get; set; }
        public int Dept_id { get; set; }
        public string Password { get; set; }
        public string Sex { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Islocked { get; set; }
        public string Ischangepwd { get; set; }
        public string Remark { get; set; }
        public string Isdeleted { get; set; }
        public Nullable<System.DateTime> Lastlogintime { get; set; }
        public string Lastloginip { get; set; }
        public int Logintimes { get; set; }
        public Nullable<System.DateTime> Createtime { get; set; }
        public int Createuserid { get; set; }
        public Nullable<System.DateTime> Updatetime { get; set; }
        public int Updateuserid { get; set; }
        public string Clientid { get; set; }
    }
}
