//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Elderly
    {
        public int Id { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public int ElderlyType { get; set; }
        public string RealName { get; set; }
        public int Age { get; set; }
        public int Gender { get; set; }
        public string IdCard { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public int HomeArea { get; set; }
        public string Spouse { get; set; }
        public string Children { get; set; }
        public int Identity { get; set; }
        public string HeadImgUrl { get; set; }
        public int AgencyId { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string EmergencyContact { get; set; }
        public int Volunteer { get; set; }
        public int AgeGroup { get; set; }
        public int IsRegistry { get; set; }
        public int IsLonely { get; set; }
        public int IsSmoking { get; set; }
        public int Alarm { get; set; }
        public int IsUseBlanket { get; set; }
        public int IsCutFuncation { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserid { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUserid { get; set; }
    }
}
