//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LifeApply
    {
        public int Id { get; set; }
        public string RealName { get; set; }
        public int Gender { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Message { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public int ApplyId { get; set; }
        public int ApplyType { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserid { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUserid { get; set; }
    }
}
