//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PensionApply
    {
        public int Id { get; set; }
        public string RealName { get; set; }
        public int Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public int Household { get; set; }
        public string Address { get; set; }
        public string DiseaseHistory { get; set; }
        public string DrugTaboo { get; set; }
        public string Guardian { get; set; }
        public int Relationship { get; set; }
        public string GuardianMobile { get; set; }
        public string GuardianAddress { get; set; }
        public int ServiceType { get; set; }
        public string Request { get; set; }
        public string ApplicantMobile { get; set; }
        public string HeadImgUrl { get; set; }
        public int ElderlyId { get; set; }
        public int Status { get; set; }
        public string Committee { get; set; }
        public int Area { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserid { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUserid { get; set; }
    }
}
