//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PublicServiceAgency
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Profile { get; set; }
        public string LegalPerson { get; set; }
        public string Tel { get; set; }
        public string Address { get; set; }
        public int ServiceType { get; set; }
        public string OtherType { get; set; }
        public string ChargeStandard { get; set; }
        public string ServiceEvaluation { get; set; }
        public int Status { get; set; }
        public Nullable<int> Area { get; set; }
        public string Point { get; set; }
        public string AgencyCode { get; set; }
        public string Contacts { get; set; }
        public string ContactsMobile { get; set; }
        public string ContactsEmail { get; set; }
        public string ContactsIdCard { get; set; }
        public string ContactsIdCardImg { get; set; }
        public string AgencyCodeImg { get; set; }
        public string BusinessLicenseImg { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserid { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUserid { get; set; }
    }
}
