//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.QYQueryServiceSoap")]
    public interface QYQueryServiceSoap {
        
        // CODEGEN: 消息 GetSlryByQyRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSlryByQy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.GetSlryByQyResponse GetSlryByQy(WebApplication1.ServiceReference1.GetSlryByQyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSlryByQy", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetSlryByQyResponse> GetSlryByQyAsync(WebApplication1.ServiceReference1.GetSlryByQyRequest request);
        
        // CODEGEN: 消息 GetQyZcryRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQyZcry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.GetQyZcryResponse GetQyZcry(WebApplication1.ServiceReference1.GetQyZcryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQyZcry", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyZcryResponse> GetQyZcryAsync(WebApplication1.ServiceReference1.GetQyZcryRequest request);
        
        // CODEGEN: 消息 GetQyxxRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQyxx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.GetQyxxResponse GetQyxx(WebApplication1.ServiceReference1.GetQyxxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQyxx", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyxxResponse> GetQyxxAsync(WebApplication1.ServiceReference1.GetQyxxRequest request);
        
        // CODEGEN: 消息 GetQyAqscxkzRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQyAqscxkz", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.GetQyAqscxkzResponse GetQyAqscxkz(WebApplication1.ServiceReference1.GetQyAqscxkzRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQyAqscxkz", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyAqscxkzResponse> GetQyAqscxkzAsync(WebApplication1.ServiceReference1.GetQyAqscxkzRequest request);
        
        // CODEGEN: 消息 GetQyCreditManualStatusRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQyCreditManualStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.GetQyCreditManualStatusResponse GetQyCreditManualStatus(WebApplication1.ServiceReference1.GetQyCreditManualStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQyCreditManualStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyCreditManualStatusResponse> GetQyCreditManualStatusAsync(WebApplication1.ServiceReference1.GetQyCreditManualStatusRequest request);
        
        // CODEGEN: 消息 GetQyThreePersonRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQyThreePerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.GetQyThreePersonResponse GetQyThreePerson(WebApplication1.ServiceReference1.GetQyThreePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQyThreePerson", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyThreePersonResponse> GetQyThreePersonAsync(WebApplication1.ServiceReference1.GetQyThreePersonRequest request);
        
        // CODEGEN: 消息 GetQyZzqkRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQyZzqk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.GetQyZzqkResponse GetQyZzqk(WebApplication1.ServiceReference1.GetQyZzqkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQyZzqk", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyZzqkResponse> GetQyZzqkAsync(WebApplication1.ServiceReference1.GetQyZzqkRequest request);
        
        // CODEGEN: 消息 CheckQyJobLicenseRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckQyJobLicense", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.CheckQyJobLicenseResponse CheckQyJobLicense(WebApplication1.ServiceReference1.CheckQyJobLicenseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckQyJobLicense", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.CheckQyJobLicenseResponse> CheckQyJobLicenseAsync(WebApplication1.ServiceReference1.CheckQyJobLicenseRequest request);
        
        // CODEGEN: 消息 GetQyFzrqkRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQyFzrqk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.GetQyFzrqkResponse GetQyFzrqk(WebApplication1.ServiceReference1.GetQyFzrqkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQyFzrqk", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyFzrqkResponse> GetQyFzrqkAsync(WebApplication1.ServiceReference1.GetQyFzrqkRequest request);
        
        // CODEGEN: 消息 CheckQyZbdlLicenseRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckQyZbdlLicense", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.CheckQyZbdlLicenseResponse CheckQyZbdlLicense(WebApplication1.ServiceReference1.CheckQyZbdlLicenseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckQyZbdlLicense", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.CheckQyZbdlLicenseResponse> CheckQyZbdlLicenseAsync(WebApplication1.ServiceReference1.CheckQyZbdlLicenseRequest request);
        
        // CODEGEN: 消息 GetQymcListByQymcRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQymcListByQymc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication1.ServiceReference1.GetQymcListByQymcResponse GetQymcListByQymc(WebApplication1.ServiceReference1.GetQymcListByQymcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQymcListByQymc", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQymcListByQymcResponse> GetQymcListByQymcAsync(WebApplication1.ServiceReference1.GetQymcListByQymcRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CiacAuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("Account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
                this.RaisePropertyChanged("PassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSlryByQy", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSlryByQyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string jgdmz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dwid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dwdm;
        
        public GetSlryByQyRequest() {
        }
        
        public GetSlryByQyRequest(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            this.CiacAuthHeader = CiacAuthHeader;
            this.jgdmz = jgdmz;
            this.dwid = dwid;
            this.dwdm = dwdm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSlryByQyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSlryByQyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetSlryByQyResult;
        
        public GetSlryByQyResponse() {
        }
        
        public GetSlryByQyResponse(string GetSlryByQyResult) {
            this.GetSlryByQyResult = GetSlryByQyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQyZcry", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQyZcryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string jgdmz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dwid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dwdm;
        
        public GetQyZcryRequest() {
        }
        
        public GetQyZcryRequest(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            this.CiacAuthHeader = CiacAuthHeader;
            this.jgdmz = jgdmz;
            this.dwid = dwid;
            this.dwdm = dwdm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQyZcryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQyZcryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetQyZcryResult;
        
        public GetQyZcryResponse() {
        }
        
        public GetQyZcryResponse(string GetQyZcryResult) {
            this.GetQyZcryResult = GetQyZcryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQyxx", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQyxxRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string dwdm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string jgdmz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dwid;
        
        public GetQyxxRequest() {
        }
        
        public GetQyxxRequest(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string dwdm, string jgdmz, string dwid) {
            this.CiacAuthHeader = CiacAuthHeader;
            this.dwdm = dwdm;
            this.jgdmz = jgdmz;
            this.dwid = dwid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQyxxResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQyxxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetQyxxResult;
        
        public GetQyxxResponse() {
        }
        
        public GetQyxxResponse(string GetQyxxResult) {
            this.GetQyxxResult = GetQyxxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQyAqscxkz", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQyAqscxkzRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string jgdmz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dwdm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dwid;
        
        public GetQyAqscxkzRequest() {
        }
        
        public GetQyAqscxkzRequest(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwdm, string dwid) {
            this.CiacAuthHeader = CiacAuthHeader;
            this.jgdmz = jgdmz;
            this.dwdm = dwdm;
            this.dwid = dwid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQyAqscxkzResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQyAqscxkzResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetQyAqscxkzResult;
        
        public GetQyAqscxkzResponse() {
        }
        
        public GetQyAqscxkzResponse(string GetQyAqscxkzResult) {
            this.GetQyAqscxkzResult = GetQyAqscxkzResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQyCreditManualStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQyCreditManualStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string jgdmz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dwdm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dwid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string nd;
        
        public GetQyCreditManualStatusRequest() {
        }
        
        public GetQyCreditManualStatusRequest(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwdm, string dwid, string nd) {
            this.CiacAuthHeader = CiacAuthHeader;
            this.jgdmz = jgdmz;
            this.dwdm = dwdm;
            this.dwid = dwid;
            this.nd = nd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQyCreditManualStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQyCreditManualStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetQyCreditManualStatusResult;
        
        public GetQyCreditManualStatusResponse() {
        }
        
        public GetQyCreditManualStatusResponse(string GetQyCreditManualStatusResult) {
            this.GetQyCreditManualStatusResult = GetQyCreditManualStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQyThreePerson", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQyThreePersonRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string jgdmz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dwid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dwdm;
        
        public GetQyThreePersonRequest() {
        }
        
        public GetQyThreePersonRequest(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            this.CiacAuthHeader = CiacAuthHeader;
            this.jgdmz = jgdmz;
            this.dwid = dwid;
            this.dwdm = dwdm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQyThreePersonResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQyThreePersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetQyThreePersonResult;
        
        public GetQyThreePersonResponse() {
        }
        
        public GetQyThreePersonResponse(string GetQyThreePersonResult) {
            this.GetQyThreePersonResult = GetQyThreePersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQyZzqk", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQyZzqkRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string jgdmz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dwid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dwdm;
        
        public GetQyZzqkRequest() {
        }
        
        public GetQyZzqkRequest(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            this.CiacAuthHeader = CiacAuthHeader;
            this.jgdmz = jgdmz;
            this.dwid = dwid;
            this.dwdm = dwdm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQyZzqkResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQyZzqkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetQyZzqkResult;
        
        public GetQyZzqkResponse() {
        }
        
        public GetQyZzqkResponse(string GetQyZzqkResult) {
            this.GetQyZzqkResult = GetQyZzqkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckQyJobLicense", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckQyJobLicenseRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string jgdmz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dwdm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dwid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string jobid;
        
        public CheckQyJobLicenseRequest() {
        }
        
        public CheckQyJobLicenseRequest(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwdm, string dwid, string jobid) {
            this.CiacAuthHeader = CiacAuthHeader;
            this.jgdmz = jgdmz;
            this.dwdm = dwdm;
            this.dwid = dwid;
            this.jobid = jobid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckQyJobLicenseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckQyJobLicenseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CheckQyJobLicenseResult;
        
        public CheckQyJobLicenseResponse() {
        }
        
        public CheckQyJobLicenseResponse(string CheckQyJobLicenseResult) {
            this.CheckQyJobLicenseResult = CheckQyJobLicenseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQyFzrqk", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQyFzrqkRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string jgdmz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dwid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dwdm;
        
        public GetQyFzrqkRequest() {
        }
        
        public GetQyFzrqkRequest(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            this.CiacAuthHeader = CiacAuthHeader;
            this.jgdmz = jgdmz;
            this.dwid = dwid;
            this.dwdm = dwdm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQyFzrqkResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQyFzrqkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetQyFzrqkResult;
        
        public GetQyFzrqkResponse() {
        }
        
        public GetQyFzrqkResponse(string GetQyFzrqkResult) {
            this.GetQyFzrqkResult = GetQyFzrqkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckQyZbdlLicense", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckQyZbdlLicenseRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string jgdmz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dwid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dwdm;
        
        public CheckQyZbdlLicenseRequest() {
        }
        
        public CheckQyZbdlLicenseRequest(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            this.CiacAuthHeader = CiacAuthHeader;
            this.jgdmz = jgdmz;
            this.dwid = dwid;
            this.dwdm = dwdm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckQyZbdlLicenseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckQyZbdlLicenseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CheckQyZbdlLicenseResult;
        
        public CheckQyZbdlLicenseResponse() {
        }
        
        public CheckQyZbdlLicenseResponse(string CheckQyZbdlLicenseResult) {
            this.CheckQyZbdlLicenseResult = CheckQyZbdlLicenseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQymcListByQymc", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQymcListByQymcRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string dwmc;
        
        public GetQymcListByQymcRequest() {
        }
        
        public GetQymcListByQymcRequest(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string dwmc) {
            this.CiacAuthHeader = CiacAuthHeader;
            this.dwmc = dwmc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQymcListByQymcResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQymcListByQymcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetQymcListByQymcResult;
        
        public GetQymcListByQymcResponse() {
        }
        
        public GetQymcListByQymcResponse(string GetQymcListByQymcResult) {
            this.GetQymcListByQymcResult = GetQymcListByQymcResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QYQueryServiceSoapChannel : WebApplication1.ServiceReference1.QYQueryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QYQueryServiceSoapClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.QYQueryServiceSoap>, WebApplication1.ServiceReference1.QYQueryServiceSoap {
        
        public QYQueryServiceSoapClient() {
        }
        
        public QYQueryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QYQueryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QYQueryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QYQueryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.GetSlryByQyResponse WebApplication1.ServiceReference1.QYQueryServiceSoap.GetSlryByQy(WebApplication1.ServiceReference1.GetSlryByQyRequest request) {
            return base.Channel.GetSlryByQy(request);
        }
        
        public string GetSlryByQy(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            WebApplication1.ServiceReference1.GetSlryByQyRequest inValue = new WebApplication1.ServiceReference1.GetSlryByQyRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwid = dwid;
            inValue.dwdm = dwdm;
            WebApplication1.ServiceReference1.GetSlryByQyResponse retVal = ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetSlryByQy(inValue);
            return retVal.GetSlryByQyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetSlryByQyResponse> WebApplication1.ServiceReference1.QYQueryServiceSoap.GetSlryByQyAsync(WebApplication1.ServiceReference1.GetSlryByQyRequest request) {
            return base.Channel.GetSlryByQyAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetSlryByQyResponse> GetSlryByQyAsync(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            WebApplication1.ServiceReference1.GetSlryByQyRequest inValue = new WebApplication1.ServiceReference1.GetSlryByQyRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwid = dwid;
            inValue.dwdm = dwdm;
            return ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetSlryByQyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.GetQyZcryResponse WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQyZcry(WebApplication1.ServiceReference1.GetQyZcryRequest request) {
            return base.Channel.GetQyZcry(request);
        }
        
        public string GetQyZcry(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            WebApplication1.ServiceReference1.GetQyZcryRequest inValue = new WebApplication1.ServiceReference1.GetQyZcryRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwid = dwid;
            inValue.dwdm = dwdm;
            WebApplication1.ServiceReference1.GetQyZcryResponse retVal = ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQyZcry(inValue);
            return retVal.GetQyZcryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyZcryResponse> WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQyZcryAsync(WebApplication1.ServiceReference1.GetQyZcryRequest request) {
            return base.Channel.GetQyZcryAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyZcryResponse> GetQyZcryAsync(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            WebApplication1.ServiceReference1.GetQyZcryRequest inValue = new WebApplication1.ServiceReference1.GetQyZcryRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwid = dwid;
            inValue.dwdm = dwdm;
            return ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQyZcryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.GetQyxxResponse WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQyxx(WebApplication1.ServiceReference1.GetQyxxRequest request) {
            return base.Channel.GetQyxx(request);
        }
        
        public string GetQyxx(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string dwdm, string jgdmz, string dwid) {
            WebApplication1.ServiceReference1.GetQyxxRequest inValue = new WebApplication1.ServiceReference1.GetQyxxRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.dwdm = dwdm;
            inValue.jgdmz = jgdmz;
            inValue.dwid = dwid;
            WebApplication1.ServiceReference1.GetQyxxResponse retVal = ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQyxx(inValue);
            return retVal.GetQyxxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyxxResponse> WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQyxxAsync(WebApplication1.ServiceReference1.GetQyxxRequest request) {
            return base.Channel.GetQyxxAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyxxResponse> GetQyxxAsync(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string dwdm, string jgdmz, string dwid) {
            WebApplication1.ServiceReference1.GetQyxxRequest inValue = new WebApplication1.ServiceReference1.GetQyxxRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.dwdm = dwdm;
            inValue.jgdmz = jgdmz;
            inValue.dwid = dwid;
            return ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQyxxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.GetQyAqscxkzResponse WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQyAqscxkz(WebApplication1.ServiceReference1.GetQyAqscxkzRequest request) {
            return base.Channel.GetQyAqscxkz(request);
        }
        
        public string GetQyAqscxkz(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwdm, string dwid) {
            WebApplication1.ServiceReference1.GetQyAqscxkzRequest inValue = new WebApplication1.ServiceReference1.GetQyAqscxkzRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwdm = dwdm;
            inValue.dwid = dwid;
            WebApplication1.ServiceReference1.GetQyAqscxkzResponse retVal = ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQyAqscxkz(inValue);
            return retVal.GetQyAqscxkzResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyAqscxkzResponse> WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQyAqscxkzAsync(WebApplication1.ServiceReference1.GetQyAqscxkzRequest request) {
            return base.Channel.GetQyAqscxkzAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyAqscxkzResponse> GetQyAqscxkzAsync(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwdm, string dwid) {
            WebApplication1.ServiceReference1.GetQyAqscxkzRequest inValue = new WebApplication1.ServiceReference1.GetQyAqscxkzRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwdm = dwdm;
            inValue.dwid = dwid;
            return ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQyAqscxkzAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.GetQyCreditManualStatusResponse WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQyCreditManualStatus(WebApplication1.ServiceReference1.GetQyCreditManualStatusRequest request) {
            return base.Channel.GetQyCreditManualStatus(request);
        }
        
        public string GetQyCreditManualStatus(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwdm, string dwid, string nd) {
            WebApplication1.ServiceReference1.GetQyCreditManualStatusRequest inValue = new WebApplication1.ServiceReference1.GetQyCreditManualStatusRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwdm = dwdm;
            inValue.dwid = dwid;
            inValue.nd = nd;
            WebApplication1.ServiceReference1.GetQyCreditManualStatusResponse retVal = ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQyCreditManualStatus(inValue);
            return retVal.GetQyCreditManualStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyCreditManualStatusResponse> WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQyCreditManualStatusAsync(WebApplication1.ServiceReference1.GetQyCreditManualStatusRequest request) {
            return base.Channel.GetQyCreditManualStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyCreditManualStatusResponse> GetQyCreditManualStatusAsync(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwdm, string dwid, string nd) {
            WebApplication1.ServiceReference1.GetQyCreditManualStatusRequest inValue = new WebApplication1.ServiceReference1.GetQyCreditManualStatusRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwdm = dwdm;
            inValue.dwid = dwid;
            inValue.nd = nd;
            return ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQyCreditManualStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.GetQyThreePersonResponse WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQyThreePerson(WebApplication1.ServiceReference1.GetQyThreePersonRequest request) {
            return base.Channel.GetQyThreePerson(request);
        }
        
        public string GetQyThreePerson(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            WebApplication1.ServiceReference1.GetQyThreePersonRequest inValue = new WebApplication1.ServiceReference1.GetQyThreePersonRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwid = dwid;
            inValue.dwdm = dwdm;
            WebApplication1.ServiceReference1.GetQyThreePersonResponse retVal = ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQyThreePerson(inValue);
            return retVal.GetQyThreePersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyThreePersonResponse> WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQyThreePersonAsync(WebApplication1.ServiceReference1.GetQyThreePersonRequest request) {
            return base.Channel.GetQyThreePersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyThreePersonResponse> GetQyThreePersonAsync(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            WebApplication1.ServiceReference1.GetQyThreePersonRequest inValue = new WebApplication1.ServiceReference1.GetQyThreePersonRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwid = dwid;
            inValue.dwdm = dwdm;
            return ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQyThreePersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.GetQyZzqkResponse WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQyZzqk(WebApplication1.ServiceReference1.GetQyZzqkRequest request) {
            return base.Channel.GetQyZzqk(request);
        }
        
        public string GetQyZzqk(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            WebApplication1.ServiceReference1.GetQyZzqkRequest inValue = new WebApplication1.ServiceReference1.GetQyZzqkRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwid = dwid;
            inValue.dwdm = dwdm;
            WebApplication1.ServiceReference1.GetQyZzqkResponse retVal = ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQyZzqk(inValue);
            return retVal.GetQyZzqkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyZzqkResponse> WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQyZzqkAsync(WebApplication1.ServiceReference1.GetQyZzqkRequest request) {
            return base.Channel.GetQyZzqkAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyZzqkResponse> GetQyZzqkAsync(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            WebApplication1.ServiceReference1.GetQyZzqkRequest inValue = new WebApplication1.ServiceReference1.GetQyZzqkRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwid = dwid;
            inValue.dwdm = dwdm;
            return ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQyZzqkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.CheckQyJobLicenseResponse WebApplication1.ServiceReference1.QYQueryServiceSoap.CheckQyJobLicense(WebApplication1.ServiceReference1.CheckQyJobLicenseRequest request) {
            return base.Channel.CheckQyJobLicense(request);
        }
        
        public string CheckQyJobLicense(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwdm, string dwid, string jobid) {
            WebApplication1.ServiceReference1.CheckQyJobLicenseRequest inValue = new WebApplication1.ServiceReference1.CheckQyJobLicenseRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwdm = dwdm;
            inValue.dwid = dwid;
            inValue.jobid = jobid;
            WebApplication1.ServiceReference1.CheckQyJobLicenseResponse retVal = ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).CheckQyJobLicense(inValue);
            return retVal.CheckQyJobLicenseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.CheckQyJobLicenseResponse> WebApplication1.ServiceReference1.QYQueryServiceSoap.CheckQyJobLicenseAsync(WebApplication1.ServiceReference1.CheckQyJobLicenseRequest request) {
            return base.Channel.CheckQyJobLicenseAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.CheckQyJobLicenseResponse> CheckQyJobLicenseAsync(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwdm, string dwid, string jobid) {
            WebApplication1.ServiceReference1.CheckQyJobLicenseRequest inValue = new WebApplication1.ServiceReference1.CheckQyJobLicenseRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwdm = dwdm;
            inValue.dwid = dwid;
            inValue.jobid = jobid;
            return ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).CheckQyJobLicenseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.GetQyFzrqkResponse WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQyFzrqk(WebApplication1.ServiceReference1.GetQyFzrqkRequest request) {
            return base.Channel.GetQyFzrqk(request);
        }
        
        public string GetQyFzrqk(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            WebApplication1.ServiceReference1.GetQyFzrqkRequest inValue = new WebApplication1.ServiceReference1.GetQyFzrqkRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwid = dwid;
            inValue.dwdm = dwdm;
            WebApplication1.ServiceReference1.GetQyFzrqkResponse retVal = ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQyFzrqk(inValue);
            return retVal.GetQyFzrqkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyFzrqkResponse> WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQyFzrqkAsync(WebApplication1.ServiceReference1.GetQyFzrqkRequest request) {
            return base.Channel.GetQyFzrqkAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQyFzrqkResponse> GetQyFzrqkAsync(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            WebApplication1.ServiceReference1.GetQyFzrqkRequest inValue = new WebApplication1.ServiceReference1.GetQyFzrqkRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwid = dwid;
            inValue.dwdm = dwdm;
            return ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQyFzrqkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.CheckQyZbdlLicenseResponse WebApplication1.ServiceReference1.QYQueryServiceSoap.CheckQyZbdlLicense(WebApplication1.ServiceReference1.CheckQyZbdlLicenseRequest request) {
            return base.Channel.CheckQyZbdlLicense(request);
        }
        
        public string CheckQyZbdlLicense(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            WebApplication1.ServiceReference1.CheckQyZbdlLicenseRequest inValue = new WebApplication1.ServiceReference1.CheckQyZbdlLicenseRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwid = dwid;
            inValue.dwdm = dwdm;
            WebApplication1.ServiceReference1.CheckQyZbdlLicenseResponse retVal = ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).CheckQyZbdlLicense(inValue);
            return retVal.CheckQyZbdlLicenseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.CheckQyZbdlLicenseResponse> WebApplication1.ServiceReference1.QYQueryServiceSoap.CheckQyZbdlLicenseAsync(WebApplication1.ServiceReference1.CheckQyZbdlLicenseRequest request) {
            return base.Channel.CheckQyZbdlLicenseAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.CheckQyZbdlLicenseResponse> CheckQyZbdlLicenseAsync(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string jgdmz, string dwid, string dwdm) {
            WebApplication1.ServiceReference1.CheckQyZbdlLicenseRequest inValue = new WebApplication1.ServiceReference1.CheckQyZbdlLicenseRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.jgdmz = jgdmz;
            inValue.dwid = dwid;
            inValue.dwdm = dwdm;
            return ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).CheckQyZbdlLicenseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ServiceReference1.GetQymcListByQymcResponse WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQymcListByQymc(WebApplication1.ServiceReference1.GetQymcListByQymcRequest request) {
            return base.Channel.GetQymcListByQymc(request);
        }
        
        public string GetQymcListByQymc(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string dwmc) {
            WebApplication1.ServiceReference1.GetQymcListByQymcRequest inValue = new WebApplication1.ServiceReference1.GetQymcListByQymcRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.dwmc = dwmc;
            WebApplication1.ServiceReference1.GetQymcListByQymcResponse retVal = ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQymcListByQymc(inValue);
            return retVal.GetQymcListByQymcResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQymcListByQymcResponse> WebApplication1.ServiceReference1.QYQueryServiceSoap.GetQymcListByQymcAsync(WebApplication1.ServiceReference1.GetQymcListByQymcRequest request) {
            return base.Channel.GetQymcListByQymcAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GetQymcListByQymcResponse> GetQymcListByQymcAsync(WebApplication1.ServiceReference1.CiacAuthHeader CiacAuthHeader, string dwmc) {
            WebApplication1.ServiceReference1.GetQymcListByQymcRequest inValue = new WebApplication1.ServiceReference1.GetQymcListByQymcRequest();
            inValue.CiacAuthHeader = CiacAuthHeader;
            inValue.dwmc = dwmc;
            return ((WebApplication1.ServiceReference1.QYQueryServiceSoap)(this)).GetQymcListByQymcAsync(inValue);
        }
    }
}
